### PR TITLE
Add support for extlinux

### PR DESCRIPTION
**Pull request by michilehr**
Add support for environments using `/boot/extlinux/extlinux.conf` like [Radxa Debain](https://wiki.radxa.com/Rockpi4/dev/u-boot/pxe)

### CODE REVIEW

**Comment by bablokb** [comment]
Nice, thanks!

**Comment by bablokb** [comment]
I have integrated this into the next-branch (where I automatically set useUUID=1 for Armbian and now for extlinux. Please check.

**Comment by michilehr** [comment]
@bablokb looks good. But then we also need to set `bootSep="="` for extlinux.conf, right?

**Comment by bablokb** [comment]
yes, already fixed.

**Pull request merged**
